### PR TITLE
Add support for tile selection

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?

It adds future support for drilldown. You can select the tiles, and the `tile` query parameter is set. 
Furthermore, the `cut` parameter will have an additional element with the current tile.

I changed the creation of the tile and added a buildTreemap method to create the treemap. I reuse the existing treemap and render it again, removing old tiles, adding new ones and updating others. 
### Up for discussion:

I added a new state `hierarchy` for handling the drilldown with tile selection. 
What do you think? I know that you said you were working on a similar approach.

### CODE REVIEW

**Comment by pudo** [comment]
Very cool, @milafrerichs - I'll study it more later, but I was wondering whether you'd seen this thread here: https://github.com/openspending/babbage/pull/8#issuecomment-167994575 - might be very relevant. 

/cc @akariv

**Comment by milafrerichs** [comment]
No, did not see it. (was not watching babbage since the merge to openspeding). 

So we basically need a hierarchy attribute in the babbage model and a way to edit the hierarchy in spendDB.ui?

**Comment by pudo** [comment]
So it looks like we could merge the hierarchies support into babbage's backend. Do you think it would be useful to have in terms of implementing this, or would you prefer to keep it independent for the moment? Obviously I'd want to integrate it into SpenDB soon (as it might make OffenerHaushalt a lot simpler), but you might just want to get something shipped for now?

**Comment by milafrerichs** [comment]
Let's integrate it into SpenDB. We need to ship soon, but I might just work on it so we can use it right away. Would make a few things I'm working on right now a lot easier (e.g. filter, breadcrumbs, etc)

But not sure where to start. 
Could you point me to the best starting point.

**Comment by pudo** [comment]
@akariv's input on this would also be invaluable.

I'd start by using his branch of babbage and making an extra screen in Spendb.ui's setup wizard for hierarchies. No UX pattern comes to mind for me right now (except drag and drop, but something simpler and more intuitive). Then, this should show up in the babbage model representation where we could use it to add a selection model for hierarchies (here; https://github.com/openspending/babbage.ui/blob/gh-pages/src/treemap.js#L144 )

Does that make any sense to you?

**Comment by milafrerichs** [comment]
Yes, that's what I thought too. Sorry, was confused again. (was looking in spendb :) )
It should be in spendb.ui, right. 
Similare to this: https://github.com/openspending/spendb.ui/blob/master/templates/dataset/dimensions.html
and the wizard starts here?
https://github.com/openspending/spendb.ui/blob/master/templates/directives/dataset_settings.html

**Comment by pudo** [comment]
Exactly! Wow, I thought this was way cryptic.

**Comment by pudo** [comment]
So just putting it in after dimensions; a screen where you can define hierarchies e.g. by clicking create, then adding dimensions in individually.

**Comment by akariv** [comment]
So it seems that you already made all the good decisions :) 

Only thing to keep in mind is the slight effect that hierarchies have on how attributes are represented (as I elaborated [here](https://github.com/openspending/babbage/pull/8#issuecomment-168723455)), but other than that it seems like it's pretty straightforward.

As for UI, I'd go with a list-of-lists approach with a drag and drop interface.
Couldn't really find anything exactly like that but [the first example here](http://rubaxa.github.io/Sortable/) is close enough.

**Comment by pwalsh** [comment]
@milafrerichs @pudo this is old and I'm assuming no longer relevant.

Because we are about to merge `feature/refactor` onto master ( https://github.com/openspending/babbage.ui/issues/16#issuecomment-221240490 ), I'm inclined to close this. Obviously, the componentized version of the treemap (and other views) supports drilldown.

@pudo do you want to merge this into the monolith code anyway? I'm not sure the implications (if any) for current SpenDB.

**Pull request closed without merging**
