### PR TITLE
RadarChart

### PR DESCRIPTION
**Pull request by larjohn**
We have created a radar (or spider) chart for visualizing aggregates in the OS Viewer. This is for the OpenBudgets.eu project.

Please review the changes and let me know of the improvements needed to be made.

### CODE REVIEW

**Comment by akariv** [comment]
Hey @kravets-levko , could you please code-review this PR?

**Comment by kravets-levko** [comment]
@akariv Code looks good. I just have one notice - about code style, but you decide whether it's critical.

**Comment by akariv** [comment]
@kravets-levko please write any comment you have here so that @larjohn could address them.

**Comment by kravets-levko** [comment]
Okay @akariv. @larjohn, your code looks good, but it would be really great if you also run js linter over the code (using `npm run review`) and fix all notices.

**Comment by larjohn** [comment]
Thanks @kravets-levko, will do so!

**Comment by kravets-levko** [comment]
Hey, @akariv! Let's merge this PR (I have no write access). I'll take care about code style by myself a bit later - I tried `npm run review` and there are a lot of notices in all parts of lib.

**Comment by akariv** [comment]
@kravets-levko done

**Comment by kravets-levko** [comment]
@akariv thanks!

**Pull request merged**
