### PR TITLE
Show message if there are too much data

### PR DESCRIPTION
**Pull request by kravets-levko**
Pivot table: allow to set limit for amount of data, and show message if there are too much data.

### CODE REVIEW

**Comment by kravets-levko** [comment]
Please don't merge it for now - I'd like to make some fixes.

**Comment by kravets-levko** [comment]
@akariv Review and merge this please.

**Comment by akariv** [comment]
Looks good to me.
Please also create an OS viewer PR for passing the messages from the translations file.

**Comment by kravets-levko** [comment]
Sorry, but can you explain me what do you mean?

**Comment by akariv** [comment]
Basically, any hard-coded string that is embedded in the code should come from the viewer, and there from the translation file - just so we know that all strings are properly localised.
See my comments in the matching viewer PR as well.

**Comment by kravets-levko** [comment]
Here is a default message, - it can be overridden (and actually is overridden) in application that uses library. I needed some default message because if you set `max-value-limit` and there will be too much cells - error message will be shown, but it cannot be empty.

**Pull request merged**
