### PR TITLE
Pagination is 1-based, not 0-based.

### PR DESCRIPTION
**Pull request by longhotsummer**
I haven't updated dist, not sure what the procedure is for that.

### CODE REVIEW

**Comment by pwalsh** [comment]
@longhotsummer because we are working on a modular version of this lib on the `feature/modern` branch, I'm reluctant to merge this myself ( see the discussion and context here https://github.com/openspending/babbage.ui/issues/16 ).

I'm also about to make `feature/modern` master, and create a new branch as a snapshot for the last "monolith" version of the codebase ( see here https://github.com/openspending/babbage.ui/issues/16#issuecomment-221240490 ).

@pudo do you want to merge this into the monolith code?

**Comment by pudo** [comment]
I'll just tag things here for SpenDB deployments before I can catch up with you guys, please feel free to merge feature/modern so that all contributions move against a common master that's actually moving.

**Comment by longhotsummer** [comment]
So it sounds like I wait for feature/modern to be merged to master, and then resubmit?

**Comment by pwalsh** [comment]
@longhotsummer if you could, that would be awesome, the code there has changed in important ways. I'll ping you when we merge.

**Pull request closed without merging**
